### ISSUE TITLE
[DESIGN]: Add breakdowns of sDEFI and sCEX to the Synths page.

### ISSUE THREAD

**Issue by Andrew-Synthetix** [Synthetixio/synthetix-website#60]
Include a way to view the compositions of sDEFI and sCEX on the Synths page. The designs should include the information available in these pages: 
https://synthetix.exchange/#/synths/sDEFI
https://synthetix.exchange/#/synths/sCEX

- [ ]  Designs made
- [ ]  Implemented in Front-End

**Comment by fritzschoff** [comment]
Is this a wanted feature?

**Comment by fritzschoff** [comment]
closing it for now. If still needed, please reopen it
